language:
  node_js
node_js:
  - "10"
  - "11"
  - "13"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
sudo:
  required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"